type: object
description: Task update request
additionalProperties: false
properties:
  title:
    type: string
    description: The title of the task
    minLength: 0
    maxLength: 100
    example: My Updated Task
